# Generated by Django 4.1.3 on 2022-11-29 17:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('estimateapp', '0003_alter_customerdetails_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='mobileNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
