# Generated by Django 4.1.3 on 2022-12-02 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estimateapp', '0004_alter_customerdetails_mobilenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimation_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_estimation', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('work_status', models.BooleanField()),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicleNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estimateapp.customerdetails')),
            ],
        ),
    ]
