# Generated by Django 4.1.3 on 2022-11-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_tbl_employee_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_employee',
            name='DOB',
        ),
    ]
