# Generated by Django 4.1.3 on 2022-11-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_remove_tbl_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_employee',
            name='userId',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
