# Generated by Django 4.1.3 on 2022-11-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('shop_name', models.CharField(max_length=200)),
                ('mobilenumber', models.IntegerField(max_length=10)),
                ('emailId', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
