# Generated by Django 4.1.3 on 2022-11-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='emailId',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
