# Generated by Django 4.1.3 on 2022-11-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
