# Generated by Django 4.1.3 on 2022-11-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimateapp', '0002_customerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='mobileNumber',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
