# Generated by Django 4.1.3 on 2022-12-02 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimateapp', '0005_estimation_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_service_name', models.CharField(max_length=200)),
                ('estimateServiceId', models.BigIntegerField()),
                ('estimateId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estimateapp.estimation_details')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_product_name', models.CharField(max_length=200)),
                ('estimateProductsId', models.BigIntegerField()),
                ('productQuanity', models.IntegerField()),
                ('estimateId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estimateapp.estimation_details')),
            ],
        ),
    ]
