# Generated by Django 4.1.3 on 2022-12-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimateapp', '0007_alter_estimation_details_date_of_estimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate_products',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='estimate_services',
            name='estimatePrice',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
