# Generated by Django 4.1.3 on 2022-12-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimateapp', '0008_estimate_products_productprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation_details',
            name='date_of_estimation',
            field=models.DateField(),
        ),
    ]
